export const products = [
  {
    name: "Bebida Láctea Pro UHT Chocolate 320 ml",
    image: "/gloria_pro.webp",
    stock: 20,
    status: "Habilitado",
    expiry: "2026-06-17",
  },
  {
    name: "Yogurt Battimix Gloria Vainilla Chocolate 146 Gr",
    image: "/batimix.webp",
    stock: 38,
    status: "Habilitado",
    expiry: "2027-07-17",
  },
  {
    name: "Empanada de Chanchito Oriental",
    image: "/empanadas.webp",
    stock: 20,
    status: "Habilitado",
    expiry: "2025-05-19",
  },
  {
    name: "Galleta Oreo Clásica 36g",
    image: "/oreo.png",
    stock: 50,
    status: "Habilitado",
    expiry: "2025-11-10",
  },
  {
    name: "Agua San Luis sin gas 625 ml",
    image: "/san_luis.jpg",
    stock: 30,
    status: "Habilitado",
    expiry: "2026-01-05",
  },
  {
    name: "Inka Chips Sabor Jalapeño",
    image: "/inka_chips.webp",
    stock: 35,
    status: "Habilitado",
    expiry: "2025-08-23",
  },
  {
    name: "Jugo de Naranja Tampico 500 ml",
    image: "/tampico.jpg",
    stock: 40,
    status: "Habilitado",
    expiry: "2026-03-30",
  },
  {
    name: "Sandwich de Pollo",
    image: "/panpollo.png",
    stock: 15,
    status: "Habilitado",
    expiry: "2025-05-20",
  },
  {
    name: "Cereal Bar Golden Cereal",
    image: "/cereal_bar.jpg",
    stock: 60,
    status: "Habilitado",
    expiry: "2026-09-14",
  },
];
